import Foundation

enum LocalizedText {
    static func text(_ key: String, language: AppLanguage) -> String {
        strings[language]?[key] ?? strings[.english]?[key] ?? key
    }

    private static let strings: [AppLanguage: [String: String]] = [
        .english: [
            "tab.explore": "Explore",
            "tab.cuisines": "Cuisines",
            "tab.saved": "Saved",
            "tab.settings": "Settings",
            "home.greeting": "Offline Chinese menu guide",
            "home.title": "Dish Passport",
            "home.searchPlaceholder": "Search mapo, dumpling, 麻婆",
            "home.recommendation": "Tonight's pick",
            "home.popular": "Popular dishes",
            "home.phrases": "Ordering phrases",
            "home.culture": "Culture notes",
            "common.seeAll": "See all",
            "common.cancel": "Cancel",
            "common.copy": "Copy phrase",
            "common.copied": "Copied",
            "common.saved": "Saved",
            "common.save": "Save",
            "common.close": "Close",
            "common.try": "Try",
            "common.addTry": "Add to Try List",
            "common.removeTry": "Remove from Try List",
            "common.liked": "Liked",
            "common.like": "Like",
            "common.reset": "Reset",
            "detail.order": "How to order",
            "detail.culture": "Culture note",
            "detail.ingredients": "Ingredients",
            "detail.bestWith": "Best with",
            "detail.heat": "Heat",
            "detail.region": "Region",
            "detail.flavor": "Flavor",
            "search.results": "%d results · offline",
            "search.empty": "No dish found. Try another English, pinyin, or Chinese name.",
            "cuisines.title": "Cuisines",
            "cuisines.subtitle": "Regional flavor map",
            "cuisine.dishes": "Representative dishes",
            "cuisine.tip": "Ordering tip",
            "cuisine.addAll": "Add all to Try List",
            "cuisine.addedAll": "Added",
            "saved.title": "Saved",
            "saved.subtitle": "Your local list",
            "saved.wantToTry": "Want to try",
            "saved.liked": "Liked",
            "saved.allSaved": "All saved",
            "saved.recent": "Recently viewed",
            "saved.empty": "Save dishes from Explore or Cuisines and they will appear here.",
            "saved.emptySection": "Nothing here yet.",
            "phrases.title": "Ordering phrases",
            "phrases.subtitle": "Useful lines at the table",
            "phrases.recent": "Recent",
            "phrases.usage": "When to use it",
            "phrases.copyChinese": "Copy Chinese",
            "settings.title": "Settings",
            "settings.subtitle": "Local first",
            "settings.language": "Language",
            "settings.automaticLanguage": "Automatic",
            "settings.privacy": "Privacy Policy",
            "settings.support": "Support",
            "settings.reset": "Reset saved dishes",
            "settings.version": "Version",
            "settings.privacyNoteTitle": "No account. No tracking.",
            "settings.privacyNoteBody": "Saved dishes stay on this iPhone. Links open only when you tap them.",
            "settings.resetTitle": "Reset saved data?",
            "settings.resetBody": "This removes saved, liked, want-to-try, and recent items from this iPhone.",
            "settings.releaseMode": "Production data only",
            "language.title": "Language",
            "language.system": "Default is inferred from system or region until you choose.",
            "heat.mild": "Mild",
            "heat.medium": "Medium",
            "heat.hot": "Hot",
            "heat.veryHot": "Very hot",
            "toast.saved": "%@ saved",
            "toast.removedSaved": "%@ removed",
            "toast.tryList": "%@ added to Try List",
            "toast.removedTry": "%@ removed from Try List",
            "toast.liked": "%@ liked",
            "toast.unliked": "%@ unliked",
            "toast.cuisineAdded": "%@ dishes added to Try List",
            "toast.cuisineAlreadyAdded": "%@ dishes are already in Try List",
            "toast.languageChanged": "Language updated",
            "toast.reset": "Saved data reset",
            "link.privacy": "https://zhouyajie.github.io/dish-passport/privacy/",
            "link.support": "https://zhouyajie.github.io/dish-passport/support/"
        ],
        .simplifiedChinese: [
            "tab.explore": "探索",
            "tab.cuisines": "菜系",
            "tab.saved": "收藏",
            "tab.settings": "设置",
            "home.greeting": "离线中国菜单指南",
            "home.title": "味游中国",
            "home.searchPlaceholder": "搜索 mapo、dumpling、麻婆",
            "home.recommendation": "今晚推荐",
            "home.popular": "热门菜品",
            "home.phrases": "点餐短语",
            "home.culture": "文化小卡",
            "common.seeAll": "查看全部",
            "common.cancel": "取消",
            "common.copy": "复制短语",
            "common.copied": "已复制",
            "common.saved": "已收藏",
            "common.save": "收藏",
            "common.close": "关闭",
            "common.try": "想尝试",
            "common.addTry": "加入想尝试",
            "common.removeTry": "移出想尝试",
            "common.liked": "已喜欢",
            "common.like": "喜欢",
            "common.reset": "重置",
            "detail.order": "怎么点",
            "detail.culture": "文化背景",
            "detail.ingredients": "主要食材",
            "detail.bestWith": "适合搭配",
            "detail.heat": "辣度",
            "detail.region": "地区",
            "detail.flavor": "口味",
            "search.results": "%d 个结果 · 离线",
            "search.empty": "没有找到菜品。试试英文、拼音或中文菜名。",
            "cuisines.title": "菜系",
            "cuisines.subtitle": "中国风味地图",
            "cuisine.dishes": "代表菜",
            "cuisine.tip": "点餐建议",
            "cuisine.addAll": "全部加入想尝试",
            "cuisine.addedAll": "已加入",
            "saved.title": "收藏",
            "saved.subtitle": "你的本地清单",
            "saved.wantToTry": "想尝试",
            "saved.liked": "已喜欢",
            "saved.allSaved": "全部收藏",
            "saved.recent": "最近浏览",
            "saved.empty": "在探索或菜系里收藏菜品后，会显示在这里。",
            "saved.emptySection": "这里暂时没有内容。",
            "phrases.title": "点餐短语",
            "phrases.subtitle": "餐桌上用得上的表达",
            "phrases.recent": "最近",
            "phrases.usage": "使用场景",
            "phrases.copyChinese": "复制中文",
            "settings.title": "设置",
            "settings.subtitle": "本地优先",
            "settings.language": "语言",
            "settings.automaticLanguage": "自动",
            "settings.privacy": "隐私政策",
            "settings.support": "支持",
            "settings.reset": "重置收藏数据",
            "settings.version": "版本",
            "settings.privacyNoteTitle": "无账号，无追踪。",
            "settings.privacyNoteBody": "保存的菜品留在这台 iPhone 上。只有你点击时才会打开外部链接。",
            "settings.resetTitle": "重置收藏数据？",
            "settings.resetBody": "这会从这台 iPhone 移除收藏、喜欢、想尝试和最近浏览。",
            "settings.releaseMode": "仅使用正式数据",
            "language.title": "语言",
            "language.system": "未手动选择时，会根据系统或地区推断，兜底英文。",
            "heat.mild": "不辣",
            "heat.medium": "中辣",
            "heat.hot": "辣",
            "heat.veryHot": "很辣",
            "toast.saved": "已收藏 %@",
            "toast.removedSaved": "已取消收藏 %@",
            "toast.tryList": "已加入想尝试：%@",
            "toast.removedTry": "已移出想尝试：%@",
            "toast.liked": "已喜欢 %@",
            "toast.unliked": "已取消喜欢 %@",
            "toast.cuisineAdded": "已将 %@ 代表菜加入想尝试",
            "toast.cuisineAlreadyAdded": "%@ 代表菜已在想尝试中",
            "toast.languageChanged": "语言已更新",
            "toast.reset": "收藏数据已重置",
            "link.privacy": "https://zhouyajie.github.io/dish-passport/privacy/zh-Hans/",
            "link.support": "https://zhouyajie.github.io/dish-passport/support/zh-Hans/"
        ],
        .japanese: [
            "tab.explore": "探す",
            "tab.cuisines": "料理系統",
            "tab.saved": "保存",
            "tab.settings": "設定",
            "home.greeting": "オフライン中国メニューガイド",
            "home.title": "中国味めぐり",
            "home.searchPlaceholder": "mapo、dumpling、麻婆を検索",
            "home.recommendation": "今夜のおすすめ",
            "home.popular": "人気料理",
            "home.phrases": "注文フレーズ",
            "home.culture": "文化メモ",
            "common.seeAll": "すべて見る",
            "common.cancel": "キャンセル",
            "common.copy": "フレーズをコピー",
            "common.copied": "コピー済み",
            "common.saved": "保存済み",
            "common.save": "保存",
            "common.close": "閉じる",
            "common.try": "食べたい",
            "common.addTry": "食べたいリストに追加",
            "common.removeTry": "食べたいリストから削除",
            "common.liked": "お気に入り",
            "common.like": "いいね",
            "common.reset": "リセット",
            "detail.order": "注文の言い方",
            "detail.culture": "文化メモ",
            "detail.ingredients": "主な食材",
            "detail.bestWith": "おすすめの組み合わせ",
            "detail.heat": "辛さ",
            "detail.region": "地域",
            "detail.flavor": "味",
            "search.results": "%d 件 · オフライン",
            "search.empty": "料理が見つかりません。英語、ピンイン、中国語名で試してください。",
            "cuisines.title": "料理系統",
            "cuisines.subtitle": "中国の味マップ",
            "cuisine.dishes": "代表料理",
            "cuisine.tip": "注文のヒント",
            "cuisine.addAll": "すべて食べたいリストへ",
            "cuisine.addedAll": "追加済み",
            "saved.title": "保存",
            "saved.subtitle": "ローカルリスト",
            "saved.wantToTry": "食べたい",
            "saved.liked": "お気に入り",
            "saved.allSaved": "すべての保存",
            "saved.recent": "最近見た料理",
            "saved.empty": "探すまたは料理系統で保存した料理がここに表示されます。",
            "saved.emptySection": "まだ何もありません。",
            "phrases.title": "注文フレーズ",
            "phrases.subtitle": "食卓で使える表現",
            "phrases.recent": "最近",
            "phrases.usage": "使う場面",
            "phrases.copyChinese": "中国語をコピー",
            "settings.title": "設定",
            "settings.subtitle": "ローカル優先",
            "settings.language": "言語",
            "settings.automaticLanguage": "自動",
            "settings.privacy": "プライバシーポリシー",
            "settings.support": "サポート",
            "settings.reset": "保存データをリセット",
            "settings.version": "バージョン",
            "settings.privacyNoteTitle": "アカウント不要。追跡なし。",
            "settings.privacyNoteBody": "保存した料理はこの iPhone に残ります。リンクはタップした時だけ開きます。",
            "settings.resetTitle": "保存データをリセットしますか？",
            "settings.resetBody": "この iPhone から保存、お気に入り、食べたい、最近見た項目を削除します。",
            "settings.releaseMode": "本番データのみ",
            "language.title": "言語",
            "language.system": "選択するまでは、システムまたは地域から推定し、英語にフォールバックします。",
            "heat.mild": "辛くない",
            "heat.medium": "中辛",
            "heat.hot": "辛い",
            "heat.veryHot": "とても辛い",
            "toast.saved": "%@ を保存しました",
            "toast.removedSaved": "%@ の保存を解除しました",
            "toast.tryList": "%@ を食べたいリストに追加しました",
            "toast.removedTry": "%@ を食べたいリストから削除しました",
            "toast.liked": "%@ をお気に入りにしました",
            "toast.unliked": "%@ のお気に入りを解除しました",
            "toast.cuisineAdded": "%@ の代表料理を食べたいリストに追加しました",
            "toast.cuisineAlreadyAdded": "%@ の代表料理はすでに追加済みです",
            "toast.languageChanged": "言語を更新しました",
            "toast.reset": "保存データをリセットしました",
            "link.privacy": "https://zhouyajie.github.io/dish-passport/privacy/ja/",
            "link.support": "https://zhouyajie.github.io/dish-passport/support/ja/"
        ]
    ]
}
